SET CURRENT SCHEMA = "BUSPROC";

CREATE BUFFERPOOL BP32K
	 ALL NODES 
	 SIZE 1000 
	 PAGESIZE 32K 
;
CREATE BUFFERPOOL BP4K
	 ALL NODES 
	 SIZE 1000 
	 PAGESIZE 4K 
;
CREATE BUFFERPOOL BP8K
	 ALL NODES 
	 SIZE 1000 
	 PAGESIZE 8K 
;

CREATE REGULAR TABLESPACE AUDIT
 	 IN NODEGROUP IBMDEFAULTGROUP 
	 PAGESIZE 4K 
	 MANAGED BY SYSTEM USING ('/home/db2inst1/ctries2/busproc/tablespaces/audit') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP4K 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
CREATE REGULAR TABLESPACE AUDIT_LARGE
 	 IN NODEGROUP IBMDEFAULTGROUP 
	 PAGESIZE 8K 
	 MANAGED BY SYSTEM USING ('/home/db2inst1/ctries2/busproc/tablespaces/audit_large') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP8K 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
-- ================================================================
-- Script generated via ERwin - Thu Jan 26 12:10:07 2006 
-- From ModelMart://mmart/Dev/MILESTONE: Business Process Control Physical Mod
-- ================================================================
--
--
SET CURRENT SCHEMA = "BUSPROC";

CREATE REGULAR TABLESPACE PARAMETER
	 PAGESIZE 4K 
	 MANAGED BY SYSTEM USING ('/home/db2inst1/ctries2/busproc/tablespaces/parameter') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP4K 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
CREATE REGULAR TABLESPACE PARAMETER_LARGE
	 PAGESIZE 8K 
	 MANAGED BY SYSTEM USING ('/home/db2inst1/ctries2/busproc/tablespaces/parameter_large') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP8K 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
CREATE REGULAR TABLESPACE PROCESS
	 PAGESIZE 4K 
	 MANAGED BY SYSTEM USING ('/home/db2inst1/ctries2/busproc/tablespaces/process') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP4K 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
CREATE REGULAR TABLESPACE PROCESS_LARGE
	 PAGESIZE 8K 
	 MANAGED BY SYSTEM USING ('/home/db2inst1/ctries2/busproc/tablespaces/process_large') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP8K 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
CREATE REGULAR TABLESPACE PRODDEFN
	 PAGESIZE 4K 
	 MANAGED BY SYSTEM USING ('/home/db2inst1/ctries2/busproc/tablespaces/proddefn') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP4K 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
CREATE REGULAR TABLESPACE SNAPMGMT
	 PAGESIZE 4K 
	 MANAGED BY SYSTEM USING ('/home/db2inst1/ctries2/busproc/tablespaces/snapmgmt') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL IBMDEFAULTBP 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
CREATE USER TEMPORARY TABLESPACE USERTEMP32
	 PAGESIZE 32K 
	 MANAGED BY SYSTEM USING ('/home/db2inst1/ctries2/busproc/tablespaces/usertemp32') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP32K 
	 OVERHEAD 10.670000 
	 TRANSFERRATE 0.040000 
	 DROPPED TABLE RECOVERY OFF 
;


-- ================================================================
-- Script generated via ERwin - Thu Jan 26 12:10:43 2006 
-- From ModelMart://mmart/Dev/MILESTONE: Chargeable Event Physical Model Versi
-- ================================================================
--
--
CREATE REGULAR TABLESPACE event
	 PAGESIZE 4K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/ctries2/busproc/tablespaces/event') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP4K 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
CREATE REGULAR TABLESPACE event_large
	 PAGESIZE 8K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/ctries2/busproc/tablespaces/event_large') 
	 EXTENTSIZE 32 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP8K 
	 OVERHEAD 1.267000E+001 
	 TRANSFERRATE 1.800000E-001 
	 DROPPED TABLE RECOVERY ON 
;
;


