-- ================================================================
-- Script generated via ERwin - Wed Jan 25 14:06:58 2006 
-- From ModelMart://mmart/Dev/MILESTONE: Snapshot Physical Model Version 12.0 FINAL
-- ================================================================
--
--

SET CURRENT SCHEMA = "SNAPSHOT";

--CREATE NODEGROUP IBMDEFAULTGROUP
-- 	ON NODES (0);
CREATE BUFFERPOOL BP32K ALL NODES  SIZE 1000 PAGESIZE 32K;
CREATE BUFFERPOOL BP4K
	 ALL NODES 
	 SIZE 1000 
	 PAGESIZE 4K 
;
CREATE BUFFERPOOL BP8K
	 ALL NODES 
	 SIZE 1000 
	 PAGESIZE 8K 
;
CREATE REGULAR TABLESPACE lang
	 PAGESIZE 8K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/tries/snapshot/tablespaces/lang' ) 
	 EXTENTSIZE 16 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP8K 
	 OVERHEAD 1.050000E+001 
	 TRANSFERRATE 1.400000E-001 
	 DROPPED TABLE RECOVERY OFF 
;
CREATE REGULAR TABLESPACE lang_large
	 PAGESIZE 32K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/tries/snapshot/tablespaces/lang_large' ) 
	 EXTENTSIZE 16 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP32K 
	 OVERHEAD 1.050000E+001 
	 TRANSFERRATE 1.400000E-001 
	 DROPPED TABLE RECOVERY OFF 
;
CREATE REGULAR TABLESPACE legseg_data
	 PAGESIZE 32K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/tries/snapshot/tablespaces/legseg_data' ) 
	 EXTENTSIZE 16 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP32K 
	 OVERHEAD 1.050000E+001 
	 TRANSFERRATE 1.400000E-001 
	 DROPPED TABLE RECOVERY OFF 
;
CREATE REGULAR TABLESPACE legseg_idx
	 PAGESIZE 4K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/tries/snapshot/tablespaces/legseg_idx' ) 
	 EXTENTSIZE 16 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP4K 
	 OVERHEAD 1.050000E+001 
	 TRANSFERRATE 1.400000E-001 
	 DROPPED TABLE RECOVERY OFF 
;
CREATE REGULAR TABLESPACE ref
	 PAGESIZE 4K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/tries/snapshot/tablespaces/ref' ) 
	 EXTENTSIZE 16 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP4K 
	 OVERHEAD 1.050000E+001 
	 TRANSFERRATE 1.400000E-001 
	 DROPPED TABLE RECOVERY OFF 
;
CREATE REGULAR TABLESPACE ref_large
	 PAGESIZE 8K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/tries/snapshot/tablespaces/ref_large' ) 
	 EXTENTSIZE 16 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP8K 
	 OVERHEAD 1.050000E+001 
	 TRANSFERRATE 1.400000E-001 
	 DROPPED TABLE RECOVERY OFF 
;
CREATE REGULAR TABLESPACE schd
	 PAGESIZE 4K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/tries/snapshot/tablespaces/schd' ) 
	 EXTENTSIZE 16 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP4K 
	 OVERHEAD 1.050000E+001 
	 TRANSFERRATE 1.400000E-001 
	 DROPPED TABLE RECOVERY OFF 
;
CREATE USER TEMPORARY TABLESPACE usertemp32
	 PAGESIZE 32K 
	 MANAGED BY SYSTEM USING ( '/home/db2inst1/tries/snapshot/tablespaces/usertemp32' ) 
	 EXTENTSIZE 16 
	 PREFETCHSIZE 16 
	 BUFFERPOOL BP32K 
	 OVERHEAD 1.050000E+001 
	 TRANSFERRATE 1.400000E+001 
	 DROPPED TABLE RECOVERY OFF 
;

CREATE REGULAR TABLESPACE LEGSEG_XML
         PAGESIZE 4K
         MANAGED BY SYSTEM USING ( '/home/db2inst1/tries/snapshot/tablespaces/legseg_xml' )
         EXTENTSIZE 16
         PREFETCHSIZE 16
         BUFFERPOOL BP4K
         OVERHEAD 1.050000E+001
         TRANSFERRATE 1.400000E-001
         DROPPED TABLE RECOVERY OFF
;

CREATE SYSTEM TEMPORARY TABLESPACE SBT_4 PAGESIZE 4K; 
CREATE SYSTEM TEMPORARY TABLESPACE SBT_8 PAGESIZE 8K BUFFERPOOL BP8K;
CREATE SYSTEM TEMPORARY TABLESPACE SBT_32 PAGESIZE 32K BUFFERPOOL BP32K;

GRANT USE OF TABLESPACE usertemp32
	TO GROUP STAFF;
