SELECT
	CARRIER_CD	AS	"carrier",
	SERVICE_NUM_STR	AS	"fltno",
	DEP_TIME_LCL	AS	"deptim",
	ARR_TIME_LCL	AS	"arrtim",
	OPER_DAYS_OF_WEEK	AS	"days",
	SERVICE_TYPE_CD	AS	"service",
	SPCFC_ARCRFT_TYPE	AS	"inpacft",
	OAG.DATEFORMAT(LEG_SEG_EFF_START_DATE,'CCYYMMDD')	AS	"efffrom",
	OAG.DATEFORMAT(LEG_SEG_EFF_END_DATE,'CCYYMMDD')	AS	"effto",
	FULL_ROUTING	AS	"routing",
	OPERATING_MARKER	AS	"operating",
	DEP_PORT_CD	AS	"depapt",
	ARR_PORT_CD	AS	"arrapt",
	RTRIM(CHAR(STOPS))	AS	"stops"
FROM SNAPSHOT.WDF_MASTER_DATA_UNENHANCED
WHERE NOT(CARRIER_CD IN('5X', 'FX', 'QB', 'XB', 'FR', 'G4'))
AND SCHED_VERSION_NAME IN('Schedules', 'Cargo Duplicate')
AND SERVICE_TYPE_CD IN('C', 'G', 'J', 'Q', 'S')
AND ( DEP_PORT_CD = 'FLL' OR ARR_PORT_CD = 'FLL' )
 AND LEG_SEG_EFF_END_DATE >= CURRENT date + 0 days AND LEG_SEG_EFF_START_DATE <= CURRENT date + 3 MONTHS
 ORDER BY DEP_PORT_CD, ARR_PORT_CD, DEP_TIME_LCL, ARR_TIME_LCL, CARRIER_CD, SERVICE_NUM with ur